import Dashboard from "components/Dashboard";
import Header from "components/Header";
import Head from "next/head";
import { ApiKeyContextProvider } from "providers/ApiKeyContextProvider";
import { EngineContextProvider } from "providers/EngineContextProvider";
import JobsContextProvider from "providers/JobsContextProvider";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sepanana</title>
        {/* <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
        <ApiKeyContextProvider>
          <EngineContextProvider>
            <JobsContextProvider>
              <Header />
              <div style={{ paddingTop: 70 }}>
                <Dashboard />
              </div>
            </JobsContextProvider>
          </EngineContextProvider>
        </ApiKeyContextProvider>
      </main>
    </>
  );
}
